name: transportasi_11
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider:
  shared_preferences:
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.6
  flutter_slidable: ^0.6.0
  screen_brightness: ^0.2.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_tts: ^3.3.3
  camera: ^0.10.5+2
  mobile_scanner: ^3.2.0
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/download.jpeg
    - assets/images/ekonomi.jpg
    - assets/images/bisnis.jpg
    - assets/images/eks.jpg
    - assets/images/priv.jpg
